version: 2.1

workflows:  
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - run:
          name: Update NPM (if needed)
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules    