version: 2.1

workflows:  
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:20

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@11.2.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules    