version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: cimg/node:18.20.7

    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@10.8.2  
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test-run
          command: npm run test
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
       
         